### ISSUE TITLE
Hide links in header based on settings

### ISSUE THREAD

**Issue by ROODAY** [BUUPE/Inquisitor#110]
Requires the settings context being created first.

- [x] Hide timeslots link if timeslot selection is closed
- [x] Hide interview link if its not an interview day
- [x] Hide deliberations if its not relevant (closed or applicant has already accepted etc)

**Comment by vitorvicente** [comment]
Fixed in https://github.com/BUUPE/Inquisitor/tree/improvements/3.0 (header no longer has a navbar, navigation is done differently, and with this in mind)
