### ISSUE TITLE
Add Recruitment Event Attendance Page

### ISSUE THREAD

**Issue by ROODAY** [BUUPE/Inquisitor#23]
Create a page that will allow taking attendance of candidates at recruitment events. This can just be a simple form of name, year, email, major, etc. Use preloading, such that if a candidate came to a previous event and starts typing their name, it should pop up and they can just prefill their information. Similarly, when applying, if a user exists from a recruitment event, pull their information to prefill some of the form.

**Comment by vitorvicente** [comment]
- [ ] Create routings
- [ ] React Component with Form to create account/log attendance
- [ ] API Post Request [FRONT END]
- [ ] API Post Request [BACK END]
- [ ] API Get Request (By name for autofill)
- [ ] Implement Autofill Box/Button on Attendance Form
- [ ] Implement Autofill Box/Button on Application Form

**Comment by vitorvicente** [comment]
Implemented in https://github.com/BUUPE/Inquisitor/tree/improvements/3.0
