### ISSUE TITLE
Add Application Page

### ISSUE THREAD

**Issue by ROODAY** [BUUPE/Inquisitor#6]
Currently candidates apply through a Google Form that is made each semester. This should become a page within Inquisitor. It will essentially be the same form, but now we can save candidate information to our database right when they apply, making it easy to auto fill information when conducting interviews.

**Comment by vitorvicente** [comment]
- [ ] Basic Form Skeleton
- [ ] Basic Form CSS
- [ ] Keep Data on Reload
- [ ] Save Data Somewhere
- [ ] Make it so the selection boxes for times actually work somehow?

**Comment by ROODAY** [comment]
Completed in 3b0783f4a0ca0529742ea52d5b867d3b48a83f2c
