### ISSUE TITLE
Look for opportunities to use optional chaining

### ISSUE THREAD

**Issue by ROODAY** [BUUPE/Inquisitor#71]
[Looks like this already has full support in major browsers and on Node](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#Browser_compatibility).

- [ ] Verify if Gatsby compiles it without the babel plugin
- [ ] Replace all instances of `obj && obj.prop` with `obj?.prop`

**Comment by vitorvicente** [comment]
Fixed in https://github.com/BUUPE/Inquisitor/tree/improvements/3.0
