### ISSUE TITLE
Create settings context for inquisitor settings

### ISSUE THREAD

**Issue by ROODAY** [BUUPE/Inquisitor#74]
Wrap root component in Gatsby so any component can grab settings using React context

**Comment by vitorvicente** [comment]
Refractor the settings to be divided into "sections" for general, interview, timeslots, deliberation

**Comment by vitorvicente** [comment]
Also include levelConfig in this context

**Comment by vitorvicente** [comment]
Fixed in https://github.com/BUUPE/Inquisitor/tree/improvements/3.0
